const mongoose = require('mongoose');
const Product = require('./models/Product');
require('dotenv').config();

const products = [
  {
    name: "Asymmetric Tulle Midi Dress",
    category: "Women",
    subCategory: "Dresses",
    price: 59.99,
    salePrice: 36.16,
    discount: 40,
    colors: ["#90EE90", "#8B008B", "#FFFFFF"],
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 25,
    availability: true,
    rating: 4.0,
    reviews: 3,
    image: "https://res.cloudinary.com/doknbffml/video/upload/v1782049699/nurfia-products/r6pqixicst5lee17ck8h.mp4",
    images: ["https://res.cloudinary.com/doknbffml/video/upload/v1782049699/nurfia-products/r6pqixicst5lee17ck8h.mp4"],
    description: "Elegant asymmetric tulle midi dress perfect for summer occasions.",
    tags: ["sale"]
  },
  {
    name: "Creased-Effect Midi Dress",
    category: "Women",
    subCategory: "Dresses",
    price: 69.99,
    salePrice: 74.11,
    discount: 19,
    colors: ["#90EE90", "#FFFFFF", "#F5DEB3"],
    sizes: ["XS", "S", "M", "L"],
    stock: 15,
    availability: true,
    rating: 4.0,
    reviews: 3,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049700/nurfia-products/uxnvzzsf7nv4bxqtriib.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049700/nurfia-products/uxnvzzsf7nv4bxqtriib.webp"],
    description: "Minimalist creased-effect midi dress for effortless everyday style.",
    tags: ["new"]
  },
  {
    name: "Draped Strapless Dress",
    category: "Women",
    subCategory: "Dresses",
    price: 66.99,
    salePrice: 54.33,
    discount: 19,
    colors: ["#90EE90", "#FFFFFF", "#000000"],
    sizes: ["S", "M", "L", "XL"],
    stock: 10,
    availability: true,
    rating: 3.3,
    reviews: 3,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049701/nurfia-products/fbrfeivccl5yfnn62vof.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049701/nurfia-products/fbrfeivccl5yfnn62vof.webp"],
    description: "Stunning draped strapless dress for special occasions.",
    tags: ["trending"]
  },
  {
    name: "Floral Crepe Midi Dress",
    category: "Women",
    subCategory: "Dresses",
    price: 78.33,
    salePrice: 61.32,
    discount: 22,
    colors: ["#FFFACD", "#FFD700", "#FFFFFF"],
    sizes: ["XS", "S", "M", "L"],
    stock: 20,
    availability: true,
    rating: 4.67,
    reviews: 6,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049702/nurfia-products/jkx1scwwf4cz3qrr51vx.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049702/nurfia-products/jkx1scwwf4cz3qrr51vx.webp"],
    description: "Beautiful floral crepe midi dress with elegant print.",
    tags: ["sale", "trending"]
  },
  {
    name: "Floral Pattern Midi Dress",
    category: "Women",
    subCategory: "Dresses",
    price: 84.33,
    salePrice: 67.11,
    discount: 21,
    colors: ["#AED6F1", "#FFFFFF", "#FFB6C1"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 18,
    availability: true,
    rating: 4.67,
    reviews: 6,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049703/nurfia-products/j2xdzqy2qtbl6lcubfl7.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049703/nurfia-products/j2xdzqy2qtbl6lcubfl7.webp"],
    description: "Romantic floral pattern midi dress with elegant draping.",
    tags: ["sale"]
  },
  {
    name: "Lace-Trimmed Midi Dress",
    category: "Women",
    subCategory: "Dresses",
    price: 149.99,
    salePrice: 129.99,
    discount: 13,
    colors: ["#8B0000", "#000000", "#FFFFFF"],
    sizes: ["XS", "S", "M", "L"],
    stock: 8,
    availability: true,
    rating: 3.3,
    reviews: 3,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049704/nurfia-products/w0m74ysecufkyhlqq3b8.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049704/nurfia-products/w0m74ysecufkyhlqq3b8.webp"],
    description: "Stunning lace-trimmed midi dress for a feminine look.",
    tags: ["new"]
  },
  {
    name: "Alternative Culture Graphic T-Shirt",
    category: "Men",
    subCategory: "T-Shirts",
    price: 29.99,
    salePrice: 18.99,
    discount: 38,
    colors: ["#FFFFFF", "#000000", "#FFA500"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 30,
    availability: true,
    rating: 4.4,
    reviews: 5,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049663/nurfia-products/wkbll732lrx1lt6tddnc.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049663/nurfia-products/wkbll732lrx1lt6tddnc.webp"],
    description: "Trendy graphic t-shirt with alternative culture prints.",
    tags: ["sale"]
  },
  {
    name: "Bermuda Jogging Shorts",
    category: "Men",
    subCategory: "Shorts",
    price: 24.40,
    salePrice: 12.66,
    discount: 53,
    colors: ["#000000", "#808080", "#FFFFFF"],
    sizes: ["S", "M", "L", "XL"],
    stock: 45,
    availability: true,
    rating: 4.0,
    reviews: 6,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049665/nurfia-products/ejosqcuhienxf6atqnc3.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049665/nurfia-products/ejosqcuhienxf6atqnc3.webp"],
    description: "Comfortable bermuda jogging shorts for casual wear.",
    tags: ["sale"]
  },
  {
    name: "Cargo Jogger Trousers",
    category: "Men",
    subCategory: "Pants",
    price: 59.33,
    salePrice: 49.99,
    discount: 14,
    colors: ["#556B2F", "#000000", "#8B4513"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 20,
    availability: true,
    rating: 4.3,
    reviews: 3,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049667/nurfia-products/uaeltmgyfltnjetammpf.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049667/nurfia-products/uaeltmgyfltnjetammpf.webp"],
    description: "Stylish cargo jogger trousers with multiple pockets.",
    tags: ["new"]
  },
  {
    name: "Oversize Short Sleeve Knit Top",
    category: "Men",
    subCategory: "Tops",
    price: 15.99,
    salePrice: 9.99,
    discount: 38,
    colors: ["#E8A090", "#FFFFFF", "#000000"],
    sizes: ["S", "M", "L", "XL"],
    stock: 35,
    availability: true,
    rating: 3.3,
    reviews: 3,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049669/nurfia-products/yn8jcgzqj7t1albyhnxf.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049669/nurfia-products/yn8jcgzqj7t1albyhnxf.webp"],
    description: "Trendy oversize knit top for a relaxed summer look.",
    tags: ["sale"]
  },
  {
    name: "Skater Jorts",
    category: "Men",
    subCategory: "Shorts",
    price: 29.99,
    salePrice: 14.29,
    discount: 53,
    colors: ["#87CEEB", "#000000", "#808080"],
    sizes: ["S", "M", "L", "XL"],
    stock: 28,
    availability: true,
    rating: 3.7,
    reviews: 3,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049670/nurfia-products/w3fdmatgantnfbxio7d0.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049670/nurfia-products/w3fdmatgantnfbxio7d0.webp"],
    description: "Cool skater jorts for a casual streetwear style.",
    tags: ["sale"]
  },
  {
    name: "Striped Crochet Shirt",
    category: "Men",
    subCategory: "Shirts",
    price: 54.90,
    salePrice: 47.50,
    discount: 14,
    colors: ["#FFFFFF", "#000000", "#F5DEB3"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 15,
    availability: true,
    rating: 3.0,
    reviews: 6,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049672/nurfia-products/qnn87la4x066hvofp47o.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049672/nurfia-products/qnn87la4x066hvofp47o.webp"],
    description: "Unique striped crochet shirt for a bohemian summer vibe.",
    tags: ["new"]
  },
  {
    name: "100% Linen Bomber Jacket",
    category: "Women",
    subCategory: "Jackets",
    price: 49.99,
    salePrice: 34.76,
    discount: 26,
    colors: ["#F5DEB3", "#000000", "#808080"],
    sizes: ["S", "M", "L", "XL"],
    stock: 20,
    availability: true,
    rating: 4.3,
    reviews: 5,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049656/nurfia-products/ntbwgbt7vigrbdskz6d0.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049656/nurfia-products/ntbwgbt7vigrbdskz6d0.webp"],
    description: "Lightweight linen bomber jacket perfect for summer evenings.",
    tags: ["new"]
  },
  {
    name: "Run & Brunch Hoodie Jacket",
    category: "Women",
    subCategory: "Jackets",
    price: 89.99,
    salePrice: 59.99,
    discount: 33,
    colors: ["#FFFFFF", "#000000", "#808080"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 15,
    availability: true,
    rating: 4.67,
    reviews: 3,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049657/nurfia-products/h6bpyu6m1ueisdwyv4vg.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049657/nurfia-products/h6bpyu6m1ueisdwyv4vg.webp"],
    description: "Cozy hoodie jacket for casual everyday wear.",
    tags: ["sale"]
  },
  {
    name: "Oversized Denim Jacket",
    category: "Women",
    subCategory: "Jackets",
    price: 74.99,
    salePrice: 54.99,
    discount: 27,
    colors: ["#87CEEB", "#000000", "#FFFFFF"],
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 18,
    availability: true,
    rating: 4.5,
    reviews: 8,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049658/nurfia-products/ooyfefypdplusaiymrt5.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049658/nurfia-products/ooyfefypdplusaiymrt5.webp"],
    description: "Trendy oversized denim jacket for a casual chic look.",
    tags: ["trending"]
  },
  {
    name: "Cropped Leather Biker Jacket",
    category: "Women",
    subCategory: "Jackets",
    price: 129.99,
    salePrice: 99.99,
    discount: 23,
    colors: ["#000000", "#8B4513", "#FFFFFF"],
    sizes: ["XS", "S", "M", "L"],
    stock: 10,
    availability: true,
    rating: 4.8,
    reviews: 12,
    image: "https://res.cloudinary.com/doknbffml/image/upload/v1782049660/nurfia-products/hre4jketfufhilqkmrwj.webp",
    images: ["https://res.cloudinary.com/doknbffml/image/upload/v1782049660/nurfia-products/hre4jketfufhilqkmrwj.webp"],
    description: "Edgy cropped leather biker jacket for a bold statement look.",
    tags: ["new", "trending"]
  }
];

mongoose.connect(process.env.MONGO_URI)
  .then(async () => {
    console.log('MongoDB Connected!');
    await Product.deleteMany();
    await Product.insertMany(products);
    console.log('Products seeded successfully!');
    process.exit();
  })
  .catch((err) => {
    console.log(err);
    process.exit(1);
  });